### ISSUE TITLE
ImportError: cannot import name ExitStack

### ISSUE THREAD

**Issue by dlezcano** [ARM-software/devlib#422]
After a git pull:

Traceback (most recent call last):
  File "/usr/local/bin/wa", line 16, in <module>
    from wa.framework.entrypoint import main
  File "/usr/local/lib/python2.7/dist-packages/wa/__init__.py", line 16, in <module>
    from wa.framework import pluginloader, signal
  File "/usr/local/lib/python2.7/dist-packages/wa/framework/signal.py", line 29, in <module>
    from wa.utils.types import prioritylist, enum
  File "/usr/local/lib/python2.7/dist-packages/wa/utils/types.py", line 46, in <module>
    from devlib.utils.types import identifier, boolean, integer, numeric, caseless_string
  File "/usr/local/lib/python2.7/dist-packages/devlib/__init__.py", line 16, in <module>
    from devlib.target import Target, LinuxTarget, AndroidTarget, LocalLinuxTarget, ChromeOsTarget
  File "/usr/local/lib/python2.7/dist-packages/devlib/target.py", line 44, in <module>
    from devlib.host import LocalConnection, PACKAGE_BIN_DIRECTORY
  File "/usr/local/lib/python2.7/dist-packages/devlib/host.py", line 26, in <module>
    from devlib.utils.misc import check_output
  File "/usr/local/lib/python2.7/dist-packages/devlib/utils/misc.py", line 44, in <module>
    from contextlib import ExitStack
ImportError: cannot import name ExitStack

**Comment by setrofim** [comment]
Python 2 is no longer supported on master. Please switch to Python 3
